[project]
name = "genie-wrapper"
version = "0.1.0"
description = "Test GeNIe python wrapper and PWA"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pysmile>=2.4.7",
    "uvicorn[standard]>=0.52.4",
]

[[tool.uv.index]]
url = "https://support.bayesfusion.com/pysmile-A/"
